name: FreeBSD CI

on: [push, pull_request, workflow_dispatch]

env:
    UBSAN_OPTIONS: print_stacktrace=1

jobs:

  test:
    name: test-bsd-systems
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: freebsd
            architecture: x86-64
            version: '14.1'

          - name: openbsd
            architecture: x86-64
            version: '7.5'

          - name: openbsd
            architecture: arm64
            version: '7.5'

          # - name: netbsd
          #   architecture: x86-64
          #   version: '10.0'

          - name: netbsd
            architecture: arm64
            version: '10.0'

    steps:
    - uses: actions/checkout@v4

    - name: Test on ${{ matrix.os.name }}
      uses: cross-platform-actions/action@v0.25.0
      with:
        operating_system: ${{ matrix.os.name }}
        architecture: ${{ matrix.os.architecture }}
        version: ${{ matrix.os.version }}
        shell: bash
        cpu_count: 2
        memory: 4G
        run: |
            uname -a
            echo $SHELL
            pwd
            ls -lhai
            whoami
            env | sort | wc -l
            clang --version
            clang++ --version

    - name: Compile and run simple program (c++17 full support)
      run: |
          clang++ test.cpp -std=c++17 -O2 -Wall -Wextra -Wpedantic -Werror -lpthread -o test_cxx17.out
          ./test_cxx17.out

    - name: Compile and run simple c++20 program (c++20 partial support)
      run: |
          clang++ test.cpp -std=c++2a -O2 -Wall -Wextra -Wpedantic -Werror -lpthread -o test_cxx20.out
          ./test_cxx20.out

    - name: Compile and run simple c++20 program (c++20 full support)
      run: |
          clang++ test.cpp -std=c++20 -O2 -Wall -Wextra -Wpedantic -Werror -lpthread -o test_cxx20.out
          ./test_cxx20.out
