name: BSD systems CI

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

env:
  UBSAN_OPTIONS: print_stacktrace=1

jobs:

  bsd-systems-clang:
    name: test-${{ matrix.os.name }}-${{ matrix.os.architecture }}-${{ matrix.os.version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: freebsd
            architecture: x86-64
            version: '14.1'
            add_pkg: pkg install

          - name: freebsd
            architecture: arm64
            version: '14.1'
            add_pkg: pkg install

          - name: openbsd
            architecture: x86-64
            version: '7.5'
            add_pkg: pkg_add

          - name: openbsd
            architecture: arm64
            version: '7.5'
            add_pkg: pkg_add

          # - name: netbsd
          #   architecture: x86-64
          #   version: '10.0'

          # - name: netbsd
          #   architecture: arm64
          #   version: '10.0'

    steps:
    - uses: actions/checkout@v4

    - name: Test on ${{ matrix.os.name }}
      uses: cross-platform-actions/action@v0.25.0
      with:
        operating_system: ${{ matrix.os.name }}
        architecture: ${{ matrix.os.architecture }}
        version: ${{ matrix.os.version }}
        shell: bash
        cpu_count: 4
        memory: 4G
        run: |
            uname -a
            echo $SHELL
            pwd
            ls -lhai
            whoami
            env | sort | wc -l

            clang --version
            clang++ --version

            sudo ${{ matrix.os.add_pkg }} gmp mpfr cmake

            clang++ test.cpp -std=c++17 -O2 -Wall -Wextra -Wpedantic -Werror -lgmp -lgmpxx -lmpfr -lpthread -o test_cxx17.out
            ./test_cxx17.out

            clang++ test.cpp -std=c++2a -O2 -Wall -Wextra -Wpedantic -Werror -lgmp -lgmpxx -lmpfr -lpthread -o test_cxx20.out
            ./test_cxx20.out

            clang++ test.cpp -std=c++20 -O2 -Wall -Wextra -Wpedantic -Werror -lgmp -lgmpxx -lmpfr -lpthread -o test_cxx20.out
            ./test_cxx20.out
