name: macOS CI

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

env:
  UBSAN_OPTIONS: print_stacktrace=1

jobs:

  macOS-cmake-clang:
    name: test-on-macOS-${{ matrix.macos_versions }}
    runs-on: macos-${{ matrix.macos_versions }}
    strategy:
      fail-fast: false
      matrix:
        macos_versions: [12, 13, 14, 15]

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew update
        brew install gcc libtool make cmake
        export PATH="/opt/homebrew/opt/make/libexec/gnubin:/usr/local/lib:$PATH"
        brew reinstall gmp@6.3.0 mpfr@6.3.0
        brew unlink gmp && brew link gmp
        brew unlink mpfr && brew link mpfr
        export LIBRARY_PATH="$LIBRARY_PATH:/opt/homebrew/lib:/usr/local/Cellar/gmp/6.3.0/lib:/usr/local/lib"
        export INCLUDE_PATH="$INCLUDE_PATH:/opt/homebrew/include:/usr/local/Cellar/gmp/6.3.0/include:/usr/local/include"

    - name: Compile and run simple program (c++17 full support)
      if: matrix.macos_versions <= 13
      run: |
        clang++ test.cpp -std=c++17 -O2 -Wall -Wextra -Wpedantic -Werror -lgmp -lgmpxx -lmpfr -lpthread -o test_cxx17.out
        ./test_cxx17.out

    - name: Compile and run simple c++20 program (c++20 partial support)
      if: matrix.macos_versions <= 13
      run: |
        clang++ test.cpp -std=c++2a -O2 -Wall -Wextra -Wpedantic -Werror -lgmp -lgmpxx -lmpfr -lpthread -o test_cxx20.out
        ./test_cxx20.out

    - name: Compile and run simple c++20 program (c++20 full support)
      if: matrix.macos_versions <= 13
      run: |
        clang++ test.cpp -std=c++20 -O2 -Wall -Wextra -Wpedantic -Werror -lgmp -lgmpxx -lmpfr -lpthread -o test_cxx20.out
        ./test_cxx20.out

    - name: Run cmake
      run: |
        chmod +x run_clang_tests_macos.sh && ./run_clang_tests_macos.sh
