name: Windows CI

# on: [push, pull_request, workflow_dispatch]
on:
  push:
    # branches:
    #   - main
  workflow_dispatch:
  pull_request:
    types: [closed]

permissions:
  contents: read

jobs:

  ubuntu-cmake-clang:
    if: github.event.pull_request.merged == false
    name: test-on-windows
    runs-on: windows-latest
    strategy:
      fail-fast: true

    steps:
    - uses: actions/checkout@v4

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64

    - name: Build sample
      run: |
        .\run_msvc_tests.bat
